### ISSUE TITLE
Missing applmsg_degc_products.h

### ISSUE THREAD

**Issue by Godeffroy** [karlhiramoto/lon4linux#1]
Hi,

In the applmsg.h you have this line :
`#include "applmsg_degc_products.h"`

and also in the makefile :
```
applmsg_degc_products.o: applmsg_degc_products.cpp
	$(CC) applmsg_degc_products.cpp -c $(INCLUDES) $(FLAGS)
```

but the 2 files are missing and compile wit errors.

Can you help me ?
Thank you

Geoffroy

**Comment by karlhiramoto** [comment]
That file should be removed  It was code unique to our products at the time, and would not be needed to communicate with other devices.
